--========================================================================================================================
--========================================================================================================================
        INSERT OR REPLACE INTO LocalizedText
			(Tag,	Language,	Text)
		VALUES
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'en_US',	"Show Cities"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'de_DE',	"Städte Anzeigen"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'es_ES',	"Mostrar Ciudades"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'fr_FR',	"Afficher Les Villes"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'it_IT',	"Mostra Città"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'ja_JP',	"都市を表示"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'ko_KR',	"도시 표시"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'pl_PL',	"Pokaż Miasta"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'pt_BR',	"Mostrar Cidades"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'ru_RU',	"Показать Города"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'zh_Hans_CN',	"显示城市"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_CITIES',		'zh_Hant_HK',	"顯示城市"),

			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'en_US',	"Unassign All Resources"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'de_DE',	"Alle Ressourcen Freigeben"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'es_ES',	"Desasignar Todos Los Recursos"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'fr_FR',	"Désaffecter Toutes Les Ressources"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'it_IT',	"Annulla Assegnazione Di Tutte Le Risorse"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'ja_JP',	"すべての資源を解除"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'ko_KR',	"모든 자원 할당 해제"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'pl_PL',	"Cofnij Przydział Wszystkich Zasobów"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'pt_BR',	"Desatribuir Todos Os Recursos"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'ru_RU',	"Отменить Назначение Всех Ресурсов"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'zh_Hans_CN',	"取消分配所有资源"),
			('LOC_UI_RESOURCE_ALLOCATION_UNASSIGN_ALL',		'zh_Hant_HK',	"取消分配所有資源"),

			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'en_US',	"Factories Only?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'de_DE',	"Nur Fabriken?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'es_ES',	"¿Solo Fábricas?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'fr_FR',	"Fabricants Seulement?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'it_IT',	"Solo Fabbriche?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'ja_JP',	"工場のみ？"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'ko_KR',	"공장만?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'pl_PL',	"Tylko Fabryki?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'pt_BR',	"Apenas Fábricas?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'ru_RU',	"Только Фабрики?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'zh_Hans_CN',	"仅工厂？"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_ONLY_FACTORIES',		'zh_Hant_HK',	"僅工廠？"),

			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'en_US',	"Distant Only?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'de_DE',	"Nur Distant?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'es_ES',	"¿Solo Distante?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'fr_FR',	"Distant Seulement?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'it_IT',	"Solo Distante?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'ja_JP',	"遠地のみ？"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'ko_KR',	"거리만?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'pl_PL',	"Tylko Dystansowe?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'pt_BR',	"Apenas Distante?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'ru_RU',	"Только Дистанционные?"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'zh_Hans_CN',	"仅远地？"),
			('LOC_UI_RESOURCE_ALLOCATION_SHOW_DISTANT_LANDS',		'zh_Hant_HK',	"僅遠地？"),

			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'en_US',	"UI"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'de_DE',	"BS"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'es_ES',	"IU"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'fr_FR',	"IU"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'it_IT',	"IU"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'ja_JP',	"UI"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'ko_KR',	"UI"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'pl_PL',	"IU"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'pt_BR',	"IU"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'ru_RU',	"ПИ"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'zh_Hans_CN',	"界面"),
			('LOC_UI_RESOURCE_ALLOCATION_UI_LABEL',		'zh_Hant_HK',	"界面");

--========================================================================================================================
--========================================================================================================================
